//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAP_TICKETS
    {
        public int TICKET_ID { get; set; }
        public string TICKET_CODE { get; set; }
        public string EVENT_NAME { get; set; }
        public string TICKET_TYPE { get; set; }
        public decimal PRICE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public System.DateTime EVENT_DATE { get; set; }
        public System.DateTime REGISTRATION_DATE { get; set; }
        public Nullable<System.DateTime> MODIFICATION_DATE { get; set; }
        public string STATUS { get; set; }
    }
}
